name: Publish Docker Image

# Ce workflow se lance uniquement quand on crée une Release sur GitHub
on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Se connecter à Docker Hub (avec tes secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Préparer l'outil de build Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Construire l'image et l'envoyer sur Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Attention : Remplace 'ton-pseudo' ci-dessous par ton pseudo Docker Hub !
          tags: |
            yasos2025/mon-projet-devops:latest
            yasos2025/mon-projet-devops:${{ github.event.release.tag_name }}